runtime: python39
entrypoint: gunicorn mysite.wsgi

instance_class: F1  # GRATIS

env_variables:
  DJANGO_SETTINGS_MODULE: "mysite.settings"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "s3f7i4h6"
  DB_HOST: "/cloudsql/djangobepp1:europe-west1:djangobepp1-instance"
  DB_PORT: "5432"

beta_settings:
  cloud_sql_instances: djangobepp1:europe-west1:djangobepp1-instance

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
