# Generated by Django 5.0.3 on 2025-08-04 15:31

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('calaix_obert', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calaix_tancat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingressat_banc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('targeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectiu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('altres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_factura', models.CharField(max_length=30)),
                ('data', models.DateTimeField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('estat', models.CharField(default='pendent', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('persona_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Targeta', 'Tarjeta')], default='Efectivo', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono', models.CharField(default=' ', max_length=10)),
                ('procedencia', models.CharField(default=' ', max_length=30)),
                ('taula_id_procedencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('nif', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comp_banc', models.CharField(max_length=200)),
                ('direccion', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pressupost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('facturat', models.CharField(default='no', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('Targeta', 'Targeta'), ('Efectivo', 'Efectiu')], default='Targeta', max_length=20)),
                ('nota', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(default='', max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('preu_distribuidor', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('marge', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('facturat', models.CharField(default='no', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Targeta', 'Targeta'), ('Efectivo', 'Efectiu')], default='Targeta', max_length=20)),
                ('nota', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('date', models.DateTimeField()),
                ('metodo_pago', models.CharField(choices=[('Efectiu', 'Efectiu'), ('Targeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Chec bancari', 'Chec bancari'), ('Domiciliacio', 'Domiciliacio')], default='Efectiu', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[myapp.models.validate_not_zero])),
                ('abono', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apuntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motiu', models.CharField(default='', max_length=200)),
                ('id_avui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.avui')),
            ],
        ),
        migrations.CreateModel(
            name='ProducteEnPressupost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.PositiveIntegerField(default=1)),
                ('pressupost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pressupost')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(default='1')),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('factura_compra', models.CharField(blank=True, max_length=100)),
                ('rebut', models.CharField(default='NO', max_length=10)),
                ('factura_compra_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.facturacompra')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEnFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('preu_venut', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('preu_distribuidor', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('marge', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facturas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProducteEnReparacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.PositiveIntegerField(default=1)),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
                ('reparacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reparacio')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Targeta', 'Tarjeta')], default='Efectivo', max_length=20)),
                ('descripcio', models.CharField(max_length=300)),
                ('material_entregat', models.CharField(max_length=300)),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ProducteReparacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
                ('reparacio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reparacions')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEnTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('preu_venut', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('preu_distribuidor', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('marge', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ticket')),
            ],
        ),
    ]
