# Generated by Django 5.0.3 on 2025-08-12 14:16
import django.db.models.deletion
import myapp.models
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300, default='')),
                ('precio', models.DecimalField(max_digits=10, decimal_places=2)),
                ('imagen', models.CharField(max_length=200)),
                ('preu_distribuidor', models.DecimalField(max_digits=10, decimal_places=2, default=1)),
                ('marge', models.DecimalField(max_digits=10, decimal_places=2, default=1)),
            ],
        ),
    ]
