# Generated by Django 5.0.3 on 2025-07-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressupost',
            name='metodo_pago',
            field=models.CharField(choices=[('Targeta', 'Targeta'), ('Efectivo', 'Efectiu')], default='Targeta', max_length=20),
        ),
        migrations.AlterField(
            model_name='pressupost',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
