# Generated by Django 5.0.3 on 2025-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_pressupost_metodo_pago_alter_pressupost_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacio',
            name='metodo_pago',
            field=models.CharField(choices=[('Targeta', 'Targeta'), ('Efectivo', 'Efectiu')], default='Targeta', max_length=20),
        ),
    ]
